mother(ann,henry).
mother(ann,mary).
mother(jane,mark).
mother(jane,francis).
mother(annette,jonathan).
mother(mary,bill).
mother(janice,louise).
mother(lucy,janet).
mother(louise,caroline).
mother(caroline,david).
mother(caroline,janet).
father(henry,jonathan).
father(john,mary).
father(francis,william).
father(francis,louise).
father(john,mark).
father(gavin,lucy).
father(john,francis).
parent(victoria,george).
parent(victoria,edward).
parent(X,Y):-mother(X,Y).
parent(X,Y):-father(X,Y).
parent(elizabeth,charles).
parent(elizabeth,andrew).
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(X,Z),ancestor(Z,Y).
child(X,Y):-mother(Y,X).
child(X,Y):-father(Y,X).
grandmother(X,Y):-mother(X,Z),mother(Z,Y).
grandmother(X,Y):-mother(X,Z),father(Z,Y).
grandfather(X,Y):-father(X,Z),mother(Z,Y).
grandfather(X,Y):-father(X,Z),father(Z,Y).
greatgrandmother(X,Y):-grandmother(X,Z),mother(Z,Y).
greatgrandmother(X,Y):-grandmother(X,Z),father(Z,Y).
greatgrandfather(X,Y):-grandfather(X,Z),mother(Z,Y).
greatgrandfather(X,Y):-grandfather(X,Z),father(Z,Y).

/* */